services:
  postgres:
    image: postgres:17.4-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: porsesh_db
      POSTGRES_USER: porsesh_user
      POSTGRES_PASSWORD: 9xz3jrd8wf
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
