name: test

on:
  - push

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make unit-tests
      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository_owner }}/${{ github.event.repository.name }}
